# Generated by Django 2.2.7 on 2020-01-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, verbose_name='脚本类别序号')),
                ('label_name', models.CharField(max_length=20, verbose_name='脚本类别名称')),
                ('label_path', models.CharField(default='null', max_length=50, verbose_name='脚本类别文件夹位置')),
            ],
            options={
                'verbose_name': '脚本分类',
                'verbose_name_plural': '脚本分类',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('nav_id', models.AutoField(primary_key=True, serialize=False, verbose_name='导航序号')),
                ('nav_name', models.CharField(max_length=20, verbose_name='导航名称')),
                ('nav_link', models.CharField(default='/', max_length=50, verbose_name='导航链接')),
            ],
            options={
                'verbose_name': '导航栏',
                'verbose_name_plural': '导航栏',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False, verbose_name='脚本序号')),
                ('script_name', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('script_file', models.CharField(max_length=50, verbose_name='脚本文件')),
                ('script_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Label', verbose_name='脚本分类')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
            },
        ),
    ]
