# Generated by Django 2.2.7 on 2022-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script_file',
            field=models.CharField(max_length=50, verbose_name='脚本文件地址'),
        ),
    ]
