# Generated by Django 2.2.5 on 2022-04-11 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 11, 20, 54, 862505), verbose_name='任务开始时间'),
        ),
    ]
