# Generated by Django 2.2.7 on 2022-04-30 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220411_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务开始时间'),
        ),
    ]
